language: python

python:
  - 2.7
  - 3.5

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y libgdal1h gdal-bin libgdal-dev

install:
  - pip install -e .\[all\]

script: 
  - pytest--cov rio_eval_calc --cov-report term-missing

after_success:
  - coveralls
